'use client';

import { useEffect, useMemo, useState } from 'react';
import { Activity, BadgeCheck, BriefcaseBusiness, CircleHelp, Copy, Database, Download, FileUp, Fingerprint, Globe2, LockKeyhole, MailCheck, Pause, Play, Radar, RefreshCw, Search, Server, ShieldCheck, Sparkles, Trash2, TriangleAlert, Upload, XCircle, Zap } from 'lucide-react';

type Verdict='deliverable'|'risky'|'undeliverable'|'unknown';

type SmtpDiagnostics={mx:string|null;attemptedMx:string[];banner:string;ehlo:string;capabilities:string[];rcptCode:number|null;rcptMessage:string;classification:{disposition:string;label:string;retryable:boolean;explanation:string};transcript:Array<{direction:'server'|'client'|'info';text:string;atMs:number}>;tls:{offered:boolean;attempted:boolean;established:boolean;authorized:boolean|null;authorizationError:string|null;protocol:string|null;cipher:string|null;subject:string|null;issuer:string|null;validFrom:string|null;validTo:string|null;fingerprint256:string|null};durationMs:number};
type SystemStatus={queue:Record<string,number>;workers:Array<{worker_id:string;hostname:string;status:string;current_job_id:string|null;processed_total:number;last_seen:string;started_at:string;online:boolean}>;jobs24h:Record<string,number>;throughput:Array<{bucket:string;checked:number;deliverable:number;risky:number;undeliverable:number;unknown_count:number}>;live:{onlineWorkers:number;checksPerMinute:number;checkedLastHour:number;unknownLastHour:number};retries:{scheduled:number;processing:number;done:number;exhausted:number};checkedAt:string};
type MonitorSnapshot={provider:string;mx:Array<{exchange:string;priority:number;ips:string[]}>;smtp:{available:boolean;mx:string|null;startTls:boolean;tlsEstablished:boolean;tlsProtocol:string|null;tlsCipher:string|null;certificateValidTo:string|null;error:string|null};checkedAt:string};
type MonitorDomain={id:number;domain:string;enabled:number;interval_minutes:number;last_check_at:string|null;last_change_at:string|null;next_check_at:string;last_hash:string|null;snapshots:Array<{id:number;changed:number;change_summary:string|null;created_at:string;snapshot:MonitorSnapshot|null}>};

type Evidence={step:string;status:'pass'|'warn'|'fail'|'info';detail:string;durationMs?:number};
type Result={email:string;valid:boolean;success:boolean;verdict:Verdict;score:number;message:string;checkedAt:string;mode:'smtp'|'domain';durationMs:number;syntax:boolean;domain:string;domainExists:boolean;mxFound:boolean;mxRecords:string[];provider:string;spf:boolean;dmarc:boolean;disposable:boolean;freeProvider:boolean;roleAccount:boolean;catchAll:boolean|null;catchAllStatus:'yes'|'no'|'inconclusive'|'not_tested';catchAllConfidence:number|null;catchAllTests:Array<{email:string;accepted:boolean;message:string}>;typoSuggestion:string|null;smtpAccepted:boolean|null;smtpMessage:string;temporaryFailure:boolean;mailboxFull:boolean;riskFlags:string[];evidence:Evidence[];providerNote:string;smtpDiagnostics:SmtpDiagnostics|null};
type DomainIntel={domain:string;resolves:boolean;provider:string;mxRecords:Array<{exchange:string;priority:number;ips:string[]}>;spf:{present:boolean;record:string|null;policy:string|null;lookupCountEstimate:number};dmarc:{present:boolean;record:string|null;policy:string|null;rua:string|null};mtaSts:{present:boolean;record:string|null};tlsRpt:{present:boolean;record:string|null};bimi:{present:boolean;record:string|null};dkimSelectors:string[];checkedAt:string};
type FinderCandidate={email:string;pattern:string;patternLabel:string;smtpAccepted:boolean;temporary:boolean;smtpCode:number|null;smtpMessage:string;mx:string;durationMs:number};
type FinderResponse={name:string;domain:string;provider:string;status:'found'|'inconclusive'|'not_found'|'temporary';found:FinderCandidate|null;candidates:FinderCandidate[];summary:{total:number;accepted:number;rejected:number;temporary:number};smtp:{mx:string|null;attemptedMx:string[];banner:string;ehlo:string};message:string};
type HistoryItem={id:number;email:string;domain:string;verdict:Verdict;score:number;provider:string|null;smtp_code:number|null;smtp_state:string|null;created_at:string;result:Result|null};
type HistoryResponse={email:string;items:HistoryItem[];comparison:{latest:HistoryItem|null;previous:HistoryItem|null;changes:string[]}};

const label:{[K in Verdict]:string}={deliverable:'Deliverable',risky:'Risky',undeliverable:'Undeliverable',unknown:'Unknown'};
function VerdictIcon({v}:{v:Verdict}){if(v==='deliverable')return <BadgeCheck/>;if(v==='risky')return <TriangleAlert/>;if(v==='unknown')return <CircleHelp/>;return <XCircle/>}
function Pill({children,kind='neutral'}:{children:React.ReactNode;kind?:string}){return <span className={`pill ${kind}`}>{children}</span>}

function Forensics({r}:{r:Result}){
  return <div className="forensics">
    <div className="sectionTitle"><Fingerprint size={18}/><div><b>Email Forensics</b><span>Evidence used to reach this verdict</span></div></div>
    <div className="timeline">{r.evidence.map((e,i)=><div className={`event ${e.status}`} key={`${e.step}-${i}`}><i/><div><b>{e.step}</b><span>{e.detail}</span>{e.durationMs!=null&&<small>{e.durationMs} ms</small>}</div></div>)}</div>
    <div className="providerNote"><ShieldCheck size={17}/><div><b>{r.provider} policy</b><span>{r.providerNote}</span></div></div>
  </div>
}

function ResultCard({r}:{r:Result}){
  return <div className={`result verdict-${r.verdict}`}>
    <div className="resultHead"><div className="resultIcon"><VerdictIcon v={r.verdict}/></div><div className="resultTitle"><span className="kicker">Verification result</span><h2>{label[r.verdict]}</h2><p>{r.email}</p></div><div className="scoreRing"><b>{r.score}</b><span>/100</span></div><button className="copy" onClick={()=>navigator.clipboard.writeText(r.email)}><Copy size={16}/></button></div>
    <div className="verdictMessage">{r.message}</div>
    <div className="resultGrid"><div><span>Provider</span><b>{r.provider}</b></div><div><span>Catch-all</span><b>{r.catchAllStatus==='yes'?`Yes · ${r.catchAllConfidence??0}%`:r.catchAllStatus==='no'?`No · ${r.catchAllConfidence??0}%`:r.catchAllStatus==='inconclusive'?'Inconclusive':'Not tested'}</b></div><div><span>SMTP</span><b>{r.smtpAccepted===null?'Not tested':r.smtpAccepted?'Accepted':'Rejected'}</b></div><div><span>Time</span><b>{r.durationMs} ms</b></div></div>
    <div className="checks"><div className="checkCard"><span><Globe2 size={17}/> Domain</span><div className="checkRows"><label>Syntax <Pill kind={r.syntax?'ok':'badpill'}>{r.syntax?'Pass':'Fail'}</Pill></label><label>MX <Pill kind={r.mxFound?'ok':'badpill'}>{r.mxFound?'Found':'Missing'}</Pill></label><label>SPF <Pill kind={r.spf?'ok':'neutral'}>{r.spf?'Present':'Missing'}</Pill></label><label>DMARC <Pill kind={r.dmarc?'ok':'neutral'}>{r.dmarc?'Present':'Missing'}</Pill></label></div></div><div className="checkCard"><span><ShieldCheck size={17}/> Risk</span><div className="checkRows"><label>Disposable <Pill kind={r.disposable?'badpill':'ok'}>{r.disposable?'Yes':'No'}</Pill></label><label>Role account <Pill kind={r.roleAccount?'neutral':'ok'}>{r.roleAccount?'Yes':'No'}</Pill></label><label>Mailbox full <Pill kind={r.mailboxFull?'neutral':'ok'}>{r.mailboxFull?'Yes':'No'}</Pill></label><label>Free provider <Pill>{r.freeProvider?'Yes':'Business/custom'}</Pill></label></div></div></div>
    {r.typoSuggestion&&<div className="suggestion"><TriangleAlert size={17}/><div><b>Possible typo</b><span>Did you mean {r.typoSuggestion}?</span></div></div>}
    {r.riskFlags.length>0&&<div className="riskFlags"><b>Risk flags</b><div>{r.riskFlags.map(x=><span key={x}>{x}</span>)}</div></div>}
    <Forensics r={r}/>
    {r.smtpDiagnostics&&<div className="smtpLab"><div className="sectionTitle"><LockKeyhole size={18}/><div><b>SMTP & TLS Lab</b><span>Direct server evidence and encrypted transport details</span></div></div><div className="smtpMetrics"><div><span>MX used</span><b>{r.smtpDiagnostics.mx||'—'}</b></div><div><span>SMTP state</span><b>{r.smtpDiagnostics.classification.label}</b></div><div><span>RCPT code</span><b>{r.smtpDiagnostics.rcptCode??'—'}</b></div><div><span>STARTTLS</span><b>{r.smtpDiagnostics.tls.established?'Established':r.smtpDiagnostics.tls.offered?'Offered':'Not advertised'}</b></div><div><span>TLS</span><b>{r.smtpDiagnostics.tls.protocol||'—'}</b><small>{r.smtpDiagnostics.tls.cipher||''}</small></div><div><span>Certificate</span><b>{r.smtpDiagnostics.tls.validTo?'Presented':'—'}</b><small>{r.smtpDiagnostics.tls.validTo?`Expires ${r.smtpDiagnostics.tls.validTo}`:''}</small></div></div><div className="smtpExplain">{r.smtpDiagnostics.classification.explanation}</div><details className="technical" open><summary>SMTP transcript</summary><div className="transcript">{r.smtpDiagnostics.transcript.map((line,i)=><div key={i} className={`tx ${line.direction}`}><span>{line.direction==='client'?'C':line.direction==='server'?'S':'•'}</span><code>{line.text}</code><small>{line.atMs}ms</small></div>)}</div></details><details className="technical"><summary>EHLO capabilities</summary><div className="capabilities">{r.smtpDiagnostics.capabilities.map(x=><code key={x}>{x}</code>)}</div></details>{r.smtpDiagnostics.tls.established&&<details className="technical"><summary>TLS certificate</summary><div className="tlsDetails"><div><span>Protocol</span><b>{r.smtpDiagnostics.tls.protocol||'—'}</b></div><div><span>Cipher</span><b>{r.smtpDiagnostics.tls.cipher||'—'}</b></div><div><span>Subject</span><b>{r.smtpDiagnostics.tls.subject||'—'}</b></div><div><span>Issuer</span><b>{r.smtpDiagnostics.tls.issuer||'—'}</b></div><div><span>Valid to</span><b>{r.smtpDiagnostics.tls.validTo||'—'}</b></div><div><span>Fingerprint</span><code>{r.smtpDiagnostics.tls.fingerprint256||'—'}</code></div></div></details>}</div>}
    {r.catchAllTests.length>0&&<details className="technical"><summary>Catch-all probe evidence</summary><div className="catchTests">{r.catchAllTests.map(t=><div key={t.email}><code>{t.email}</code><span className={t.accepted?'accepted':'rejected'}>{t.accepted?'Accepted':'Rejected'}</span></div>)}</div></details>}
  </div>
}

function HistoryPanel({history}:{history:HistoryResponse|null}){
  if(!history||!history.items.length)return null;
  return <div className="historyPanel"><div className="sectionTitle"><Activity size={18}/><div><b>Verification History</b><span>Compare how this mailbox behaves over time</span></div></div>{history.comparison.changes.length>0&&<div className="changeSummary">{history.comparison.changes.map(x=><span key={x}>{x}</span>)}</div>}<div className="historyTable"><div className="historyRow historyHeader"><span>Checked</span><span>Verdict</span><span>Score</span><span>SMTP</span><span>Provider</span></div>{history.items.slice(0,8).map(h=><div className="historyRow" key={h.id}><span>{new Date(h.created_at).toLocaleString()}</span><span>{label[h.verdict]||h.verdict}</span><span>{h.score}/100</span><span>{h.smtp_code??'—'} {h.smtp_state||''}</span><span>{h.provider||'Unknown'}</span></div>)}</div></div>
}

function InfrastructureGraph({intel}:{intel:DomainIntel}){
  return <div className="infraGraph"><div className="infraRoot"><Globe2 size={18}/><b>{intel.domain}</b><small>{intel.provider}</small></div><div className="infraBranches">{intel.mxRecords.map(mx=><div className="infraBranch" key={mx.exchange}><div className="infraMx"><Server size={16}/><b>MX {mx.priority}</b><code>{mx.exchange}</code></div><div className="infraIps">{mx.ips.length?mx.ips.map(ip=><span key={ip}>{ip}</span>):<span>IP unresolved</span>}</div></div>)}</div><div className="infraSecurity"><span className={intel.spf.present?'good':'missing'}>SPF</span><span className={intel.dmarc.present?'good':'missing'}>DMARC</span><span className={intel.dkimSelectors.length?'good':'missing'}>DKIM</span><span className={intel.mtaSts.present?'good':'missing'}>MTA-STS</span><span className={intel.tlsRpt.present?'good':'missing'}>TLS-RPT</span><span className={intel.bimi.present?'good':'missing'}>BIMI</span></div></div>
}

function ThroughputChart({points}:{points:SystemStatus['throughput']}){
  const max=Math.max(1,...points.map(x=>x.checked));
  return <div className="throughputBox"><div className="sectionTitle"><Activity size={18}/><div><b>Live throughput</b><span>Verification volume over the last 30 minutes</span></div></div><div className="throughputBars">{points.length?points.map((p,i)=><div className="throughputBar" key={p.bucket} title={`${p.bucket}: ${p.checked} checks`}><i style={{height:`${Math.max(4,(p.checked/max)*100)}%`}}/><span>{i%5===0?new Date(p.bucket.replace(' ','T')).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'}):''}</span></div>):<div className="emptyState">No recent verification traffic.</div>}</div></div>
}

export default function Home(){
  const [tab,setTab]=useState<'verify'|'finder'|'domain'|'bulk'|'workers'|'monitor'>('verify');
  const [email,setEmail]=useState('');const[result,setResult]=useState<Result|null>(null);const[busy,setBusy]=useState(false);const[error,setError]=useState('');const[smtp,setSmtp]=useState(true);
  const [person,setPerson]=useState('');const[companyDomain,setCompanyDomain]=useState('');const[finder,setFinder]=useState<FinderResponse|null>(null);
  const [domain,setDomain]=useState('');const[intel,setIntel]=useState<DomainIntel|null>(null);
  const [bulk,setBulk]=useState('');const[bulkResults,setBulkResults]=useState<Result[]>([]);const[jobId,setJobId]=useState<string|null>(null);const[job,setJob]=useState<any>(null);
  const [system,setSystem]=useState<SystemStatus|null>(null);const[history,setHistory]=useState<HistoryResponse|null>(null);const[monitorDomains,setMonitorDomains]=useState<MonitorDomain[]>([]);const[monitorDomain,setMonitorDomain]=useState('');const[monitorInterval,setMonitorInterval]=useState(60);
  const parseBulk=(t:string)=>[...new Set(t.split(/[\n,;\s]+/).map(v=>v.trim()).filter(v=>v.includes('@')))];
  const stats=useMemo(()=>({total:bulkResults.length,deliverable:bulkResults.filter(x=>x.verdict==='deliverable').length,risky:bulkResults.filter(x=>x.verdict==='risky').length,invalid:bulkResults.filter(x=>x.verdict==='undeliverable').length,unknown:bulkResults.filter(x=>x.verdict==='unknown').length}),[bulkResults]);
  async function post(url:string,body:any){setBusy(true);setError('');try{const res=await fetch(url,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});const data=await res.json();if(!res.ok)throw new Error(data.error||'Request failed');return data;}catch(e){setError(e instanceof Error?e.message:'Request failed');return null;}finally{setBusy(false)}}
  async function verify(){const d=await post('/api/verify',{email,ignoreSMTP:!smtp});if(d){setResult(d);try{const h=await fetch(`/api/history?email=${encodeURIComponent(d.email)}`,{cache:'no-store'});const hd=await h.json();if(h.ok)setHistory(hd)}catch{}}}
  async function findEmail(){const d=await post('/api/email-finder',{name:person,domain:companyDomain});if(d)setFinder(d)}
  async function inspect(){const d=await post('/api/domain-intelligence',{domain});if(d)setIntel(d)}
  async function startBulk(){const emails=parseBulk(bulk);const d=await post('/api/bulk-verify',{emails,ignoreSMTP:!smtp});if(d?.jobId){setJobId(d.jobId);setJob({status:'queued',total:emails.length,processed:0})}}
  async function control(action:string){if(!jobId)return;const d=await post(`/api/jobs/${jobId}/control`,{action});if(d?.jobId)setJobId(d.jobId)}
  useEffect(()=>{if(!jobId)return;let stopped=false;const tick=async()=>{try{const r=await fetch(`/api/jobs/${jobId}`,{cache:'no-store'});const d=await r.json();if(stopped)return;setJob(d.job);setBulkResults(d.results||[]);if(['completed','failed','cancelled'].includes(d.job?.status))return;}catch{}setTimeout(tick,1200)};tick();return()=>{stopped=true}},[jobId]);
  function importFile(e:React.ChangeEvent<HTMLInputElement>){const f=e.target.files?.[0];if(!f)return;const rd=new FileReader();rd.onload=()=>setBulk(String(rd.result||''));rd.readAsText(f)}
  async function loadSystem(){try{const r=await fetch('/api/system-status',{cache:'no-store'});const d=await r.json();if(r.ok)setSystem(d)}catch{}}
  async function loadMonitoring(){try{const r=await fetch('/api/monitoring',{cache:'no-store'});const d=await r.json();if(r.ok)setMonitorDomains(d.domains||[])}catch{}}
  async function monitorAction(action:string,id?:number){const d=await post('/api/monitoring',action==='add'?{action,domain:monitorDomain,intervalMinutes:monitorInterval}:{action,id});if(d){if(action==='add')setMonitorDomain('');await loadMonitoring()}}
  useEffect(()=>{if(tab!=='workers')return;loadSystem();const t=setInterval(loadSystem,3000);return()=>clearInterval(t)},[tab]);
  useEffect(()=>{if(tab!=='monitor')return;loadMonitoring();const t=setInterval(loadMonitoring,8000);return()=>clearInterval(t)},[tab]);
  function csv(){const header=['Email','Verdict','Score','Provider','Catch All Status','Catch All Confidence','Message'];const rows=[header,...bulkResults.map(r=>[r.email,r.verdict,String(r.score),r.provider,r.catchAllStatus,String(r.catchAllConfidence),r.message])];const text=rows.map(row=>row.map(v=>`"${String(v).replaceAll('"','""')}"`).join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type:'text/csv'}));a.download='verification-results.csv';a.click();URL.revokeObjectURL(a.href)}
  return <main className="shell"><div className="glow glow1"/><div className="glow glow2"/><nav className="nav"><div className="brand"><div className="logo"><MailCheck size={22}/></div><div><strong>coldmailpro emailverifier</strong><span>Email Intelligence Platform</span></div></div><div className="status"><span className="pulse"/> Engine online</div></nav>
    <section className="hero"><div className="eyebrow"><Sparkles size={16}/> Verification · Finder · Forensics · Domain Intelligence</div><h1>Know what exists.<br/><span>Know why.</span></h1><p>Mailbox verification with provider-aware SMTP heuristics, catch-all confidence, forensic evidence, direct SMTP company email discovery, domain security intelligence and adaptive bulk processing.</p></section>
    <section className="workspace"><div className="tabs wide"><button className={tab==='verify'?'active':''} onClick={()=>setTab('verify')}><Search size={17}/> Verify</button><button className={tab==='finder'?'active':''} onClick={()=>setTab('finder')}><BriefcaseBusiness size={17}/> Email Finder</button><button className={tab==='domain'?'active':''} onClick={()=>setTab('domain')}><Globe2 size={17}/> Domain Intel</button><button className={tab==='bulk'?'active':''} onClick={()=>setTab('bulk')}><Upload size={17}/> Bulk</button><button className={tab==='workers'?'active':''} onClick={()=>setTab('workers')}><Server size={17}/> Workers</button><button className={tab==='monitor'?'active':''} onClick={()=>setTab('monitor')}><Radar size={17}/> Monitor</button></div>
      {(tab==='verify'||tab==='bulk')&&<div className="modebar"><div><ShieldCheck size={18}/><div><b>Deep SMTP mode</b><small>{smtp?'Provider-aware SMTP + catch-all probes':'DNS-only verification'}</small></div></div><button className={`switch ${smtp?'on':''}`} onClick={()=>setSmtp(!smtp)}><span/></button></div>}
      {error&&<div className="error"><TriangleAlert size={18}/>{error}</div>}
      {tab==='verify'&&<><div className="verifybox"><label>Email address</label><div className="inputrow"><input value={email} onChange={e=>setEmail(e.target.value)} onKeyDown={e=>e.key==='Enter'&&verify()} placeholder="name@company.com"/><button onClick={verify} disabled={busy||!email}><Zap size={18}/>{busy?'Analyzing…':'Verify email'}</button></div></div>{result&&<><ResultCard r={result}/><HistoryPanel history={history}/></>}</>}
      {tab==='finder'&&<><div className="verifybox"><label>Find corporate email by SMTP</label><div className="finderGrid"><input value={person} onChange={e=>setPerson(e.target.value)} placeholder="John Smith"/><input value={companyDomain} onChange={e=>setCompanyDomain(e.target.value)} placeholder="company.com"/><button onClick={findEmail} disabled={busy||!person||!companyDomain}><Search size={18}/>{busy?'Running SMTP…':'Find email'}</button></div><small>Tests every generated candidate directly against the recipient MX using EHLO/HELO, MAIL FROM and RCPT TO. No learning, no guessed pattern ranking.</small></div>{finder&&<div className="finderResults"><div className={`bestMatch ${finder.status!=='found'?'ambiguous':''}`}><span>{finder.status==='found'?'SMTP FOUND':finder.status==='not_found'?'NOT FOUND':finder.status==='temporary'?'TEMPORARY SMTP RESPONSE':'SMTP INCONCLUSIVE'}</span>{finder.found?<><h2>{finder.found.email}</h2><div><Pill kind="ok">RCPT {finder.found.smtpCode??'250'} accepted</Pill><b>Uniquely accepted</b></div></>:<><h2>{finder.summary.accepted>1?`${finder.summary.accepted} candidates accepted`:'No unique mailbox identified'}</h2></>}<p>{finder.message}</p><div className="patternMemory"><ShieldCheck size={16}/><span>Provider: <b>{finder.provider}</b> · MX: <b>{finder.smtp.mx||'Unavailable'}</b></span></div></div><div className="candidateList finderCandidates">{finder.candidates.map((r,i)=><div key={r.email}><span>#{i+1}</span><div className="candidateIdentity"><b>{r.email}</b><small>{r.patternLabel}</small><small>{r.smtpMessage}</small></div><div className="candidateScores"><em>SMTP <strong>{r.smtpCode??'—'}</strong></em><em><strong>{r.temporary?'Temporary':r.smtpAccepted?'Accepted':'Rejected'}</strong></em></div></div>)}</div><details className="technical"><summary>SMTP session evidence</summary><div className="catchTests"><div><code>MX</code><span>{finder.smtp.mx||'None'}</span></div><div><code>Banner</code><span>{finder.smtp.banner}</span></div><div><code>EHLO/HELO</code><span>{finder.smtp.ehlo}</span></div></div></details></div>}</>}
      {tab==='domain'&&<><div className="verifybox"><label>Domain intelligence</label><div className="inputrow"><input value={domain} onChange={e=>setDomain(e.target.value)} onKeyDown={e=>e.key==='Enter'&&inspect()} placeholder="company.com"/><button onClick={inspect} disabled={busy||!domain}><Globe2 size={18}/>{busy?'Inspecting…':'Inspect domain'}</button></div></div>{intel&&<div className="domainPanel"><div className="domainHero"><div><span>Mail infrastructure</span><h2>{intel.domain}</h2><p>{intel.provider}</p></div><Pill kind={intel.resolves?'ok':'badpill'}>{intel.resolves?'Domain online':'Unresolved'}</Pill></div><InfrastructureGraph intel={intel}/><div className="domainMetrics"><div><span>SPF</span><b>{intel.spf.present?'Present':'Missing'}</b><small>{intel.spf.policy||'No policy'}</small></div><div><span>DMARC</span><b>{intel.dmarc.present?'Present':'Missing'}</b><small>{intel.dmarc.policy||'No policy'}</small></div><div><span>DKIM</span><b>{intel.dkimSelectors.length||0} selectors</b><small>{intel.dkimSelectors.join(', ')||'Common selectors not found'}</small></div><div><span>MTA-STS</span><b>{intel.mtaSts.present?'Present':'Missing'}</b></div><div><span>TLS-RPT</span><b>{intel.tlsRpt.present?'Present':'Missing'}</b></div><div><span>BIMI</span><b>{intel.bimi.present?'Present':'Missing'}</b></div></div><details className="technical" open><summary>MX infrastructure</summary><div className="mxList">{intel.mxRecords.map(mx=><div key={mx.exchange}><b>{mx.priority}</b><code>{mx.exchange}</code><span>{mx.ips.join(', ')||'IP unresolved'}</span></div>)}</div></details>{intel.spf.record&&<details className="technical"><summary>SPF record</summary><code>{intel.spf.record}</code></details>}{intel.dmarc.record&&<details className="technical"><summary>DMARC record</summary><code>{intel.dmarc.record}</code></details>}</div>}</>}
      {tab==='bulk'&&<><div className="verifybox bulkbox"><label>Bulk verification</label><textarea value={bulk} onChange={e=>setBulk(e.target.value)} placeholder={'alice@example.com\nbob@company.com'}/><div className="bulkActions"><small>{parseBulk(bulk).length} unique addresses</small><div className="actionGroup"><label className="fileButton"><FileUp size={17}/> Import<input type="file" accept=".csv,.txt" onChange={importFile}/></label><button onClick={startBulk} disabled={busy||!parseBulk(bulk).length}><Activity size={18}/> Start job</button></div></div></div>{job&&<div className="jobbar"><div><b>Job {job.status}</b><code>{jobId}</code></div><div className="jobprogress"><span style={{width:`${job.total?Math.round((job.processed/job.total)*100):0}%`}}/></div><div className="jobcontrols">{job.status==='running'&&<button onClick={()=>control('pause')}><Pause size={15}/> Pause</button>}{job.status==='paused'&&<button onClick={()=>control('resume')}><Play size={15}/> Resume</button>}{!['completed','failed','cancelled'].includes(job.status)&&<button onClick={()=>control('cancel')}>Cancel</button>}{Number(job.unknown)>0&&<button onClick={()=>control('retry-unknown')}>Retry unknown</button>}</div></div>}{(job||bulkResults.length>0)&&<div className="bulkResults"><div className="stats"><div><span>Total</span><b>{stats.total}</b></div><div><span>Deliverable</span><b>{stats.deliverable}</b></div><div><span>Risky</span><b>{stats.risky}</b></div><div><span>Invalid</span><b>{stats.invalid}</b></div><div><span>Unknown</span><b>{stats.unknown}</b></div><button onClick={csv}><Download size={17}/> Export</button></div><div className="table"><div className="tr th"><span>Email</span><span>Verdict</span><span>Score</span><span>Provider</span><span>Catch-all</span></div>{bulkResults.map(r=><div className="tr" key={r.email}><span>{r.email}</span><span>{label[r.verdict]}</span><span><b>{r.score}</b>/100</span><span>{r.provider}</span><span>{r.catchAllStatus==='yes'?`Yes ${r.catchAllConfidence??0}%`:r.catchAllStatus==='no'?'No':r.catchAllStatus==='inconclusive'?'Inconclusive':'—'}</span></div>)}</div></div>}</>}
      {tab==='workers'&&<div className="opsPanel"><div className="sectionTitle"><Server size={18}/><div><b>Worker & Queue Operations</b><span>Live BullMQ workload and worker heartbeats</span></div><button className="miniButton" onClick={loadSystem}><RefreshCw size={15}/> Refresh</button></div>{system?<><div className="liveFleet"><div><span>Online workers</span><b>{system.live.onlineWorkers}</b></div><div><span>Checks / min</span><b>{system.live.checksPerMinute}</b></div><div><span>Last hour</span><b>{system.live.checkedLastHour}</b></div><div><span>Auto retries</span><b>{Number(system.retries.scheduled||0)+Number(system.retries.processing||0)}</b></div></div><div className="opsStats"><div><span>Waiting</span><b>{system.queue.waiting||0}</b></div><div><span>Active</span><b>{system.queue.active||0}</b></div><div><span>Delayed</span><b>{system.queue.delayed||0}</b></div><div><span>Failed</span><b>{system.queue.failed||0}</b></div><div><span>Completed</span><b>{system.queue.completed||0}</b></div></div><ThroughputChart points={system.throughput||[]}/><div className="retrySummary"><span>Greylist retry scheduler</span><b>{system.retries.scheduled||0} scheduled</b><b>{system.retries.processing||0} processing</b><b>{system.retries.done||0} recovered/done</b><b>{system.retries.exhausted||0} exhausted</b></div><div className="workerList">{system.workers.length?system.workers.map(w=><div key={w.worker_id}><span className={`workerDot ${w.online?'online':'offline'}`}/><div><b>{w.hostname}</b><code>{w.worker_id}</code></div><div><strong>{w.online?w.status:'offline'}</strong><small>{Number(w.processed_total).toLocaleString()} processed</small></div><div><small>Current job</small><code>{w.current_job_id||'idle'}</code></div></div>):<div className="emptyState">No worker heartbeat found. Start <code>email-verifier-worker</code>.</div>}</div></>:<div className="emptyState">Loading worker status…</div>}</div>}
      {tab==='monitor'&&<div className="monitorPanel"><div className="verifybox"><label>Monitor a mail domain</label><div className="monitorAdd"><input value={monitorDomain} onChange={e=>setMonitorDomain(e.target.value)} placeholder="company.com"/><select value={monitorInterval} onChange={e=>setMonitorInterval(Number(e.target.value))}><option value={15}>15 min</option><option value={60}>Hourly</option><option value={360}>6 hours</option><option value={1440}>Daily</option></select><button onClick={()=>monitorAction('add')} disabled={busy||!monitorDomain}><Radar size={17}/> Add monitor</button></div><small>Tracks MX, SPF, DMARC, DKIM, MTA-STS, TLS-RPT, BIMI, SMTP availability and TLS certificate changes.</small></div><div className="monitorList">{monitorDomains.length?monitorDomains.map(d=>{const latest=d.snapshots?.[0];const snap=latest?.snapshot;return <div className="monitorCard" key={d.id}><div className="monitorHead"><div><span className={`workerDot ${d.enabled?'online':'offline'}`}/><h3>{d.domain}</h3><small>Every {d.interval_minutes} min · {snap?.provider||'Awaiting first check'}</small></div><div className="monitorButtons"><button onClick={()=>monitorAction('check',d.id)}><RefreshCw size={14}/> Check now</button><button onClick={()=>monitorAction('toggle',d.id)}>{d.enabled?'Pause':'Resume'}</button><button className="danger" onClick={()=>monitorAction('delete',d.id)}><Trash2 size={14}/></button></div></div>{snap&&<div className="monitorMetrics"><div><span>SMTP</span><b>{snap.smtp.available?'Online':'Offline'}</b></div><div><span>MX</span><b>{snap.smtp.mx||snap.mx?.[0]?.exchange||'—'}</b></div><div><span>STARTTLS</span><b>{snap.smtp.startTls?'Yes':'No'}</b></div><div><span>TLS</span><b>{snap.smtp.tlsProtocol||'—'}</b></div><div><span>Certificate</span><b>{snap.smtp.certificateValidTo||'—'}</b></div></div>}{latest&&<div className={`changeLine ${latest.changed?'changed':''}`}><b>{latest.changed?'Change detected':'Latest check'}</b><span>{latest.change_summary||'No change summary'}</span><small>{new Date(latest.created_at).toLocaleString()}</small></div>} {d.snapshots?.slice(1).map(x=><div className="historyLine" key={x.id}><span>{x.changed?'Changed':'Stable'}</span><b>{x.change_summary}</b><small>{new Date(x.created_at).toLocaleString()}</small></div>)}</div>}):<div className="emptyState">No monitored domains yet.</div>}</div></div>}
    </section>
    <section className="features"><div><Fingerprint/><b>Email Forensics</b><p>See the evidence chain that produced every verdict.</p></div><div><BriefcaseBusiness/><b>Email Finder</b><p>Run direct SMTP recipient checks across generated corporate addresses.</p></div><div><Globe2/><b>Domain Intelligence</b><p>MX, SPF, DMARC, DKIM, MTA-STS, TLS-RPT and BIMI signals.</p></div><div><Database/><b>Adaptive workers</b><p>MySQL history, Redis queueing and provider/domain-aware backoff.</p></div></section>
    <footer>coldmailpro emailverifier · MySQL + Redis/BullMQ · Runs on your infrastructure</footer></main>
}
